name: Docker Test & Publish

on:
  push:
    # branches:
    #   - "main"
    tags:
      - "*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/docker.yml"
      - ".vscode/**"
      - "doc/**"
      - ".gitignore"
      - "LICENSE"
      - "README"
  pull_request:
    branches:
      - "main"
    paths:
      - "Dockerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  base:
    runs-on: ubuntu-latest
    name: Build base image
    steps:
      # Configure build environment
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Authenticate with GHCR
      - name: Login to Github Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: teamabron
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/base:stage
          cache-from: type=gha,scope=buildx-base-multi-arch
          cache-to: type=gha,scope=buildx-base-multi-arch,mode=max

  publish:
    
    needs: [base]
    runs-on: ubuntu-latest
    env:
      CONFIG_BRANCH: stage
      CLONE_DIR: $GITHUB_WORKSPACE/config
      CONFIG_FILE: $GITHUB_WORKSPACE/config/apps/pep-backend/kustomization.yaml
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        project: [delta, bonfire]
    name: Build ${{ matrix.project }} image
    steps:
      # Configure build environment
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Authenticate with Docker Hub and GHCR
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     registry: docker.io
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: teamabron
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # Resolve the correct project
      - uses: kanga333/variable-mapper@master
        id: export
        with:
          key: "${{ matrix.project }}"
          map: |
            {
              "delta": {
                "name: "pepchat-backend",
                "path": "crates/delta",
                "tag": "${{ secrets.DOCKERHUB_USERNAME }}/server"
              },
              "bonfire": {
                "name: "pepchat-bonfire",
                "path": "crates/bonfire",
                "tag": "${{ secrets.DOCKERHUB_USERNAME }}/bonfire"
              }
            }
          export_to: output

      # Configure metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            # docker.io/${{ steps.export.outputs.tag }}
            ghcr.io/${{ steps.export.outputs.tag }}

      # Build crate image
      - name: Publish
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ${{ steps.export.outputs.path }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/base:stage
          labels: ${{ steps.meta.outputs.labels }}
  
      - name: Checkout Configuration Repository
        run: |
            echo "Cloning configuration repository"
            mkdir -p $CLONE_DIR
            git clone -b $CONFIG_BRANCH ${{ secrets.K8_CONFIG_REPO }} $CLONE_DIR
      
      - name: Set Up Git Identity
        run: |
            cd $CLONE_DIR
            git config user.email "ci@abron.co"
            git config user.name "CI Bot"


      - name: Update Image Tag in kustomization.yaml
        run: |
            awk -v name=${{ steps.export.outputs.name }} -v tag="  newTag: ${{ github.sha }}" '$0 ~ "^- name: " name "$" {found=1} found && /^  newTag:/ {sub(/^  newTag: .*/, tag); found=0} {print} ' "$CONFIG_FILE" > temp.yml && mv temp.yml "$CONFIG_FILE"
            awk -v name=${{ steps.export.outputs.name }} -v new_image="  newName: ghcr.io/${{ steps.export.outputs.tag }}" ' $0 ~ "^- name: " name "$" {found=1} found && /^  newName:/ {sub(/^  newName: .*/, new_image); found=0} {print} ' "$CONFIG_FILE" > temp.yml && mv temp.yml "$CONFIG_FILE"


      - name: Commit & Push Changes
        run: |
            cd $CLONE_DIR
            git add .
            git commit -am "Update image tag to the latest commit ${{ github.sha }}"
            git push origin $CONFIG_BRANCH  
